

POST http://localhost:8083/connectors
Accept: application/json
Content-Type: application/json

< test.json
###

DELETE http://localhost:8083/connectors/moviesdemo-connector
###

DELETE http://localhost:8081/subjects/events-value
###